name: Pulse
options:
  bundleIdPrefix: com.huangsunquan
  deploymentTarget:
    macOS: "14.0"
configs:
  Debug-Internal: debug
  Release-Internal: release
  Debug-Public: debug
  Release-Public: release
configFiles:
  Debug-Internal: xcconfig/Pulse-Internal.xcconfig
  Release-Internal: xcconfig/Pulse-Internal.xcconfig
  Debug-Public: xcconfig/Pulse-Public.xcconfig
  Release-Public: xcconfig/Pulse-Public.xcconfig
targets:
  Pulse:
    type: application
    platform: macOS
    sources:
      - path: Pulse
    settings:
      base:
        ENABLE_PREVIEWS: YES
        ENABLE_HARDENED_RUNTIME: NO
        INFOPLIST_KEY_LSUIElement: YES
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.developer-tools
        INFOPLIST_KEY_NSHighResolutionCapable: YES
      configs:
        Debug-Internal:
          PRODUCT_NAME: Pulse Internal
          PRODUCT_MODULE_NAME: Pulse
        Release-Internal:
          PRODUCT_NAME: Pulse Internal
          PRODUCT_MODULE_NAME: Pulse
        Debug-Public:
          PRODUCT_NAME: Pulse
          PRODUCT_MODULE_NAME: Pulse
        Release-Public:
          PRODUCT_NAME: Pulse
          PRODUCT_MODULE_NAME: Pulse
  PulseTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: PulseTests
        excludes:
          - "Fixtures/**"
    dependencies:
      - target: Pulse
    settings:
      base:
        PRODUCT_NAME: PulseTests
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/Pulse.app/Contents/MacOS/Pulse
schemes:
  Pulse:
    build:
      targets:
        Pulse: all
        PulseTests: [test]
    test:
      config: Debug-Public
      targets:
        - PulseTests
    run:
      config: Debug-Public
    profile:
      config: Release-Public
    analyze:
      config: Debug-Public
    archive:
      config: Release-Public
